name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Устанавливаем конкретную старую версию Nightly от 2019 года
    - name: Install Legacy Rust Toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2019-09-01
        targets: i686-pc-windows-msvc

    # ХАК ДЛЯ УСКОРЕНИЯ: заставляем Git скачивать только самый последний снимок индекса без истории
    - name: Configure Git for Cargo Speedup
      run: |
        git config --global core.autocrlf false
        git config --global fetch.recurseSubmodules false
      shell: bash

    - name: Build Release
      run: cargo build --release --target i686-pc-windows-msvc --verbose
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: d3d9-dll-x86
        path: target/i686-pc-windows-msvc/release/d3d9.dll
        if-no-files-found: error
